# Generated by Django 2.2.7 on 2019-12-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(default='Enter Body of blog here'),
        ),
    ]
